const NONE = 4,
    UP = 3,
    LEFT = 2,
    DOWN = 1,
    RIGHT = 11,
    WAITING = 5,
    PAUSE = 6,
    PLAYING = 7,
    COUNTDOWN = 8,
    EATEN_PAUSE = 9,
    DYING = 10,
    WALL = 0,
    BISCUIT = 1,
    EMPTY = 2,
    BLOCK = 3,
    PILL = 4,
    FPS = 30,
    BISCUIT_SCORE = 5,
    PILL_SCORE = 50,
    MAP_BACKGROUND = 'white',
    WALL_COLOR = "blue",
    BISCUIT_COLOR = 'red',
    BISCUIT_SIZE = 15,
    MAX_PILL_SIZE = 50;

const KEY = {
    'N': 78,
    'P': 80,
    'S': 83,
};

export {
    WALL,
    BISCUIT,
    EMPTY,
    BLOCK,
    PILL,
    FPS,
    NONE,
    UP,
    LEFT,
    DOWN,
    RIGHT,
    WAITING,
    PAUSE,
    PLAYING,
    COUNTDOWN,
    EATEN_PAUSE,
    DYING,
    BISCUIT_SCORE,
    PILL_SCORE,
    KEY,
    MAP_BACKGROUND,
    BISCUIT_COLOR,
    BISCUIT_SIZE,
    WALL_COLOR,
    MAX_PILL_SIZE
};